dist: trusty

language: python

python:
    - '2.7'
    - '3.4'

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - python-numpy python3-numpy

before_install:
  - pip install pytest pytest-cov

install:
  - pip install .

script:
  - cd test && pytest --cov meshzoo

after_success:
  - bash <(curl -s https://codecov.io/bash)
