dist: trusty

language: python

python:
    - '2.7'
    - '3.6'

addons:
  apt:
    packages:
      - python-numpy python3-numpy

before_install:
  - pip install pytest pytest-cov pylint

install:
  - pip install .

script:
  - pylint meshzoo
  - pylint test/*.py
  - cd test && pytest --cov meshzoo

after_success:
  - bash <(curl -s https://codecov.io/bash)
