version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3
    steps:
      - run: pip3 install -U pytest pytest-cov excode --user
      - checkout
      - run: pip3 install .[all] --user
      # extract code snippets from readme
      - run: excode README.md test/readme_test.py --filter python
      - run: echo -e "import meshzoo\n$(cat test/readme_test.py)" > test/readme_test.py
      # The actual test
      - run:
          command: pytest --cov meshzoo
          working_directory: test/
          environment:
            MPLBACKEND: Agg
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
